data:
  name: https://gist.githubusercontent.com/simplymathematics/8c6c04bd151950d5ea9e62825db97fdd/raw/d6a22cdb42a1db624c89f0298cb4f654d3812703/kdd_nsl.csv
  sample:
    random_state: 0
    shuffle: true
    stratify: true
    test_size: 1000
    time_series: false
    train_size: 5000
  sklearn_pipeline:
    pipeline:
      encoder:
        kwargs:
          handle_unknown: use_encoded_value
          unknown_value: -1
        name: sklearn.preprocessing.OrdinalEncoder
      preprocessor:
        kwargs:
          with_mean: true
          with_std: true
        name: sklearn.preprocessing.StandardScaler
  target: label
files:
  data_dir: data
  files:
    adv_predictions_file: models/reports/train/e745877fcf1e29f92e139d3d41017a8a/adv_predictions.json
    adv_probabilities_file: models/reports/train/e745877fcf1e29f92e139d3d41017a8a/adv_probabilities.json
    attack_file: models/attacks/attack.pkl
    data_file: models/data/8079bd842507e3e2304c81e0360db636.pkl
    model_file: models/models/7b60136ba6a4dc09e998c342f162fc9c.pkl
    params_file: models/reports/train/e745877fcf1e29f92e139d3d41017a8a/params.yaml
    predictions_file: models/reports/train/e745877fcf1e29f92e139d3d41017a8a/predictions.json
    probabilities_file: models/reports/train/e745877fcf1e29f92e139d3d41017a8a/probabilities.json
    score_dict_file: models/reports/train/e745877fcf1e29f92e139d3d41017a8a/score_dict.json
    test_labels_file: models/reports/train/e745877fcf1e29f92e139d3d41017a8a/test_labels.json
    train_labels_file: models/reports/train/e745877fcf1e29f92e139d3d41017a8a/train_labels.json
  model_dir: models
  name: e745877fcf1e29f92e139d3d41017a8a
  reports: reports
  stage: train
kwargs:
  direction: maximize
model:
  art:
    library: sklearn-svc
    name: 9b86c9b0cfb8d5e872a0126c0611580a
    pipeline:
      initialize:
        kwargs: {}
        name: initialize
  data:
    name: https://gist.githubusercontent.com/simplymathematics/8c6c04bd151950d5ea9e62825db97fdd/raw/d6a22cdb42a1db624c89f0298cb4f654d3812703/kdd_nsl.csv
    sample:
      random_state: 0
      shuffle: true
      stratify: true
      test_size: 1000
      time_series: false
      train_size: 5000
    sklearn_pipeline:
      pipeline:
        encoder:
          kwargs:
            handle_unknown: use_encoded_value
            unknown_value: -1
          name: sklearn.preprocessing.OrdinalEncoder
        preprocessor:
          kwargs:
            with_mean: true
            with_std: true
          name: sklearn.preprocessing.StandardScaler
    target: label
  init:
    kwargs:
      C: 0.01
      coef0: 0.01
      gamma: scale
      kernel: rbf
      max_iter: 10
      probability: true
      random_state: 0
    name: sklearn.svm.SVC
  library: sklearn-svc
  name: 3af2177580d586c1759ab626a4fbf5f6
  trainer:
    kwargs: {}
name: e745877fcf1e29f92e139d3d41017a8a
scorers:
  scorers:
    accuracy:
      alias: accuracy_score
      args:
      - y_true
      - y_pred
      direction: maximize
      name: sklearn.metrics.accuracy_score
      params: {}
    log_loss:
      alias: log_loss
      args:
      - y_true
      - y_pred
      direction: minimize
      name: sklearn.metrics.log_loss
      params: {}
