gcp_region: "us-central1"
gcp_zone: "us-central1-c"
gcp_machine_type: "e2-medium"
gcp_image_project: "ubuntu-os-cloud"
gcp_image_family: "ubuntu-2204-lts"
gcp_ssh_user: "mr.salehsedghpour"
gcp_ssh_pub_key_file: "/Users/msaleh/.ssh/id_ed25519.pub"
node_count: 3
