defaults:
    - _self_
    - data: torch_cifar100
    - model: torch_cifar100
    - attack: default
    - files: cifar100
    - scorers: default
    - override hydra/sweeper : optuna
    - override hydra/sweeper/sampler : grid
    - override hydra/launcher : joblib
stage : '???'
direction : [maximize, minimize]
optimizers : [accuracy, train_time]
_target_ : deckard.base.experiment.Experiment
optimizers : accuracy
hydra:
  run:
    dir: ${files.directory}/${files.reports}/${stage}/logs
  sweep:
    dir: ${files.directory}/${stage}/${model.init.name}
    subdir : ${hydra.sweeper.study_name}/${hydra.job.num}
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 123
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 1 # default : 10
      n_ei_candidates: 1 # default : 24
      multivariate: true
      warn_independent_sampling: true
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: minimize
    storage: null
    study_name: sphere
    n_trials: 3
    n_jobs: 1
    max_failure_rate: 0.0
  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: 1
    prefer : processes
    verbose: 10
    timeout: null
    pre_dispatch: n_jobs
    batch_size: auto
    temp_folder: /tmp/deckard
    max_nbytes: 100000
    mmap_mode: r
