cluster_name: k8s-cluster
gpu_count: 1
gpu_driver_version: default
gpu_type: nvidia-tesla-v100
image_family: ubuntu-2204-lts
image_project: ubuntu-os-cloud
machine_type: n1-standard-2
max_nodes: 1
min_nodes: 1
mount_directory: /mnt/filestore
num_nodes: 1
persistent_volume_claim: ./IaaC/gcp/pvc.yaml
pod: ./IaaC/gcp/pod.yaml
storage_config: ./IaaC/gcp/sclass.yaml
